name: Github actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/upload-artifact@v2
      with:
        name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - run: flutter --version
      - run: flutter pub get
      - run: flutter build apk --dart-define=key=minha_key_apk
      - run: flutter build appbundle --dart-define=key=minha_key_appbundle

      


